import Head from 'next/head'
import Header from 'components/Header'
import { ArrowRightIcon, PlusIcon } from '@heroicons/react/24/outline'
import React, { useState } from 'react'

export default function Index() {
  const [searchTerm, setSearchTerm]= useState("")
  return (
    <div>
      <Head>
        <title>Client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <Header/>

      <main>
        <header className="bg-white shadow">
          <div className="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
            <h1 className="text-3xl font-bold tracking-tight text-gray-900">Client</h1>
            
          </div>
        </header>

        <div className="w-full  py-2 sm:px-6 lg:px-17">
          {<div className='w-full'>
            <div>
             <input     
                className="rounded-lg m-2 border-4 border border-gray-400"
                 type="text"
                 name="searchBar"
                 id="searchBar"
                 value={searchTerm}
                 placeholder='Rechercher'
                 onChange={(e) => {setSearchTerm(e.target.value)}}
             />

                <a href="pages/client/new.tsx" className='col-end-30'> Ajouter un client
                    <button
                        type="button"
                        className="rounded-full m-2 bg-green-700 p-1 text-neutral-50 hover:text-gray-400 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"
                        >
                        <PlusIcon className="h-6 w-6" aria-hidden="true" />
                    </button>
                </a>
                </div>
            </div>}
          <div className="px-4 py-6 sm:px-0">
            
            <div className="h-96 rounded-lg border-4 border border-gray-200">
              <p>le .map ici</p>
              <div>
                <div> Montrer le client</div>
                <a href="pages/client/[id]/index.tsx">
                    <button
                        type="button"
                        
                        className="rounded-full bg-gray-800 p-1 text-neutral-50 hover:text-gray-400 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"
                        >
                        <ArrowRightIcon className="h-6 w-6" aria-hidden="true" />
                    </button>
                </a>
              </div>
            </div>
          </div>
          {}
        </div>
      </main>

    </div>
  )
}
