import Head from 'next/head'
import Header from '../../components/Header';
import { PlusIcon} from '@heroicons/react/24/outline'
import Modal from "react-modal";
import React, { Component, FunctionComponent, useState } from 'react';
import { useQuery } from 'react-query';
import { useForm } from 'react-hook-form';
import { useRouter } from 'next/router';



export default function New() {
  const [role, setRole] = useState(1)
  const { register, handleSubmit } = useForm()
  const router = useRouter()
  const onSubmit = async (data: any) => {
        await fetch('/api/users', {method: 'POST', body: JSON.stringify(data)})
         router.push('/')
      }
  
  return (
    <div>
      <Head>
        <title>admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <Header/>

      <main>
        <header className="bg-white shadow">
          <div className="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
            <h1 className="text-3xl font-bold tracking-tight text-gray-900">Client</h1>
          </div>
        </header>

        <div className="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
          { <div>
                <div>Creation d'un user</div>
            </div>
          }
          <div className="px-4 py-6 sm:px-0">
            
            <div className="h-96 w-200 rounded-lg border-4 border border-gray-400">
              <form onSubmit={handleSubmit(onSubmit)} method='POST' >
                <div>
                    <label>Nom du user
                        <input {...register('name')} name="name"className="rounded-lg m-2 border-4 border border-gray-400"></input>
                    </label>
                </div>
                <div>
                    <label>email
                        <input {...register('email')} name="email" className="rounded-lg w-200 m-2 w-900 border-4 border border-gray-400"></input>
                    </label>
                </div>
                <div>
                    <label>password
                        <input {...register('password')} name="password" className="rounded-lg w-200 m-2 w-900 border-4 border border-gray-400"></input>
                    </label>
                </div>
                <div>
                    
                </div>
                <div>
          
               
    
                </div>
                <button
                    type="submit" 
                    className="rounded-full bg-gray-800 p-1 text-neutral-50 hover:text-gray-400 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"
                    >Créer
                </button>
              </form>
            </div>
          </div>
          {}
        </div>
      </main>

    </div>
  )}