import Head from 'next/head'
import Header from '../components/Header'
import { PlusIcon } from '@heroicons/react/24/outline'

export default function Account() {
 
  return (
    <div>
      <Head>
        <title>Votre Compte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main>
        <header className="bg-white shadow"> 
          <div className="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
            <h1 className="text-3xl font-bold tracking-tight text-gray-900">Votre Compte</h1>
            
          </div>
        </header>

        <div className="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
          {}
          <div className="px-4 py-6 sm:px-0">
            
            <div className="h-96 rounded-lg border-4 border border-gray-200">
              <p>le .map ici</p>
            </div>
          </div>
          {}
        </div>
      </main>

    </div>
  )
}
