import Head from 'next/head'
import Header from '../components/Header'
import { PlusIcon } from '@heroicons/react/24/outline'

export default function Client() {
 
  return (
    <div>
      <Head>
        <title>Franchise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main>
        <header className="bg-white shadow">
          <div className="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
            <h1 className="text-3xl font-bold tracking-tight text-gray-900">Client</h1>
            
          </div>
        </header>

        <div className="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
          {<div>
                <div> Ajouter un client</div>
                <a href="NewClient">
                    <button
                        type="button"
                        className="rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"
                        >
                        <PlusIcon className="h-6 w-6" aria-hidden="true" />
                    </button>
                </a>
            </div>}
          <div className="px-4 py-6 sm:px-0">
            
            <div className="h-96 rounded-lg border-4 border border-gray-200">
              <p>le .map ici</p>
            </div>
          </div>
          {}
        </div>
      </main>

    </div>
  )
}
